global:
  # Default namespace for the ArgoCD OperatorGroup and related resources
  namespace: argocd-1

argocdInstance:
  # ArgoCD instance configuration
  name: argocd-1
  # Specify ArgoCD configuration here...
  timeout:
    reconciliation: 30s
argocdImageUpdater:
  enabled: true
  config:
    # -- Argo CD Image Update log level
    logLevel: "info"

    # -- Argo CD Image Updater registries list configuration. More information [here](https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/)
    registries: []
      # - name: Docker Hub
      #   api_url: https://registry-1.docker.io
      #   ping: yes
      #   credentials: secret:foo/bar#creds
      #   defaultns: library
      # - name: Google Container Registry
      #   api_url: https://gcr.io
      #   prefix: gcr.io
      #   ping: no
      #   credentials: pullsecret:foo/bar
      # - name: RedHat Quay
      #   api_url: https://quay.io
      #   ping: no
      #   prefix: quay.io
      #   credentials: env:REGISTRY_SECRET
      # - name: ECR
      #   api_url: https://123456789.dkr.ecr.eu-west-1.amazonaws.com
      #   prefix: 123456789.dkr.ecr.eu-west-1.amazonaws.com
      #   ping: yes
      #   insecure: no
      #   credentials: ext:/scripts/auth1.sh
    #   credsexpire: 10h
